### ISSUE TITLE
Any way to listen the end of animation?

### ISSUE THREAD

**Issue by dmoreno** [ember-animation/liquid-fire#16]
This project is awesome!

But, is there any way to listen the end of animation?

I need run some code only when the animation inside a #liquid-with has finished.

**Comment by Leooo** [comment]
Another use case: I'm using a tutorial based on bootstrap popover components, which automatically open themselves under certain controller-based conditions.

Now I need to wait for any liquid-fire transition to terminate before opening them, or the (absolute) position of the popovers will be off. My container for popovers is the body of the document, as liquid-fire's overflow:hidden features can prevent them from rendering inside the views being transitioned. Not sure how to resolve this, trying to observe each willTransition / didTransition now and to setup a "isTransitioning" flag on the ApplicationController, but I'm not sure it will work and it feels ugly.

**Comment by ffaubry** [comment]
I'm not sure if this is solving some of the scenarios mentioned above but it solved my issue.
When a user clicked on an item card in a div (A), I wanted to show a div (B) sliding-in from the right side. For this, I used a liquid-if helper. The issue is that the content of the div (A) gets re-organized as the containing div width is reduced. When it's done, I need to be sure that the item clicked by the user that triggered the whole transition is still visible in the div (A). This is leading to the issue of knowing when the transition is done to setup the scroll in the div (A). 
Here is how I solved it...
1) Created a custom transition called 'apply-and-alert':
```
import { stop } from "liquid-fire";

export default function (transition, opts) {

  stop(this.oldElement);
  return this.lookup(transition).apply(this, [opts || {}]).then(function () { 
    if (!this.newElement)
      return;
    this.newElement.trigger('liquid-transition-end');
  }.bind(this));
}
```

2) In the app.js file added the definition for the new custom event:
```
App = Ember.Application.extend({
  customEvents: {
    'liquid-transition-end': 'liquidTransitionEnd'
  }
});
```

3) In the component that encapsulate the div (A) and the liquid-if:
```
export default Ember.Component.extend({ 
    liquidTransitionEnd: function() { 
    // Update the scroll position based on x, y, and z
  }
});
```

**Comment by Leooo** [comment]
Thanks for sharing this @ffaubry
