### ISSUE TITLE
Using other transitions, like moveOver

### ISSUE THREAD

**Issue by tehmaestro** [ember-animation/liquid-fire#177]
Hi, I went through the repository and saw some additional transitions like move-over and flex-grow.
 I believe move-over is exactly what I need. I want to have the newView slide upwards, over the oldView, and then remove the oldView. In reverse, I'd like to have the newView be displayed under the oldView, and then animate the oldView downwards, so it reveals the newView from under it.

  I tried using this with:
```
   ...
     this.use('moveOver', 'toUp')
   ...
```
  but it doesn't work. There is no animation, the newView just appears over the oldView.
  Any ideas? Thank you.

**Comment by ef4** [comment]
move-over slides both the old and new views together, so not what you want. There isn't a built in transition that does, but it should be very easy to add. 

I suggest copying move-over into your own new transition and editing it to take out the part of the animation you don't want.

Since your case is not symmetric, you probably want two different transitions. One that slides the new view on top of the old, and one that puts the new view behind the old and slides the old away.

**Comment by tehmaestro** [comment]
Ok, cool, i'll try and make my own transitions.

**Comment by melissaroman** [comment]
@tehmaestro: Did you end up making this type of transition? I'm looking to do the same thing.

**Comment by tehmaestro** [comment]
Hi, I used a different transition in the end. But it really is super easy to create your own.
