### ISSUE TITLE
liquid-with renders nothing with a falsey value

### ISSUE THREAD

**Issue by totallymike** [ember-animation/liquid-fire#258]
If you pass a falsey value to liquid-with, like so:

``` handlebars
{{#liquid-with somethingFalse as value}}
  Some other content
  {{value}}
{{/liquid-with}}
```

Then nothing is rendered in the helper.  To demonstrate, I forked the repo and broke the liquid-with docs page: https://github.com/ef4/liquid-fire/compare/master...totallymike:broken-with

**Comment by ef4** [comment]
This is intentional, because it matches the behavior of Ember's `with`.

Ember's `with` has slowly fallen out of favor, primarily because of the move away from scope-changing helpers. It's not about to go away, but it's less useful than it once was.

Before liquid-fire 1.0 I plan to deprecate `liquid-with` in favor of giving `liquid-bind` a block form, in addition to its existing inline form. So people can do both `{{liquid-bind someThing}}` and `{{#liquid-bind someThing as |s|}} My {{s}}!{{/liquid-bind}}`. liquid-bind does not have this potentially-confusing behavior of not rendering anything when the content is falsey.

**Comment by Name-less** [comment]
I have the same issue using liquid-bind, is that normal ?
My initial value is 0. 
When i load the page the value binded is 0, nothing is displayed. 
If the value pass from 1 to 0, so the 0 is well displayed and animated.

**Comment by ef4** [comment]
That's not expected, please share a reproduction if you can. Thanks.

**Comment by Name-less** [comment]
This looks to happen when i load my model value after the DOM has been built. With other values than 0, they are displayed correctly, with 0 they are not.

I tried to reproduce it by forking the project or in other places in my project without success ... i use a workaround but it is not the best way. I tell you if I isolate the cause
