### ISSUE TITLE
Not animating when transitioning from a child route to another parent route

### ISSUE THREAD

**Issue by ptraceur** [ember-animation/liquid-fire#501]
For example, when I go from `/packages/list` to `/profile` or vice-versa it doesn't animate. But `/packages` to `/packages/list` does animate. For this case should I place a liquid outlet  tag on a special place?

Transition code I have:
```js
this.transition(
    this.fromRoute('packages.list'),
    this.toRoute('profile'),
    this.use('toLeft'),
    this.reverse('toRight')
);
```

The same happens, for example, from `/packages/list` to `/products/sold`.

Thanks,
cheers from Portugal.

**Comment by ef4** [comment]
You have one outlet transitioning between "packages" and "profile", and another outlet inside "packages" transitioning between "packages.list" and any other routes in there like "packages.index". There is no outlet that ever transitions from "packages.list" to "profile". This is not a liquid-fire thing, this is how all Ember outlets work, including `liquid-outlet`.

**Comment by ptraceur** [comment]
So there is no way I can make a transition effect between this two routes?

**Comment by ef4** [comment]
You can, you just need to design it in a way that matches your route hierarchy (or adjust your route hierarchy so it really matches the experience).

```js
this.transition(
    this.fromRoute('packages'),
    this.toRoute('profile'),
    this.use('toLeft'),
    this.reverse('toRight')
);
```

**Comment by ptraceur** [comment]
Using: 
```js
this.fromRoute('packages')
//instead of
this.fromRoute('packages.list'),
```

will animate a transition between packages.list to profile, or I had to make some other modifications? I'm a bit confused, since I'm new to ember

**Comment by ef4** [comment]
No worries. Yes, that change will cause every route under "packages"
including "packages.list" to be included in the animation rule.

**Comment by ptraceur** [comment]
Ok I see, so this
```js
this.transition(
    this.fromRoute('packages'),
    this.toRoute('profile'),
    this.use('fade'),
    this.reverse('fade')
);
```
will work, but this

```js
this.transition(
    this.fromRoute('packages'),
    this.toRoute('profile.edit'),
    this.use('toLeft'),
    this.reverse('toRight')
);
```
will not, and therefore if I have these two bits of code, the only animation it will do is a Fade and never will do a left/right transition. So, its not possible to have different animation styles because of how ember is architecture, or is it possible?

**Comment by ef4** [comment]
There are a couple ways to do what you want.

One is to adjust the route hierarchy so that it more closely matches the experience you're trying to convey. If you really want different animations for going from `packages` to `profile.edit` vs from `packages` to `profile.index`, that suggests to me that those two profile routes are really both distinct places that may belong at the top level. (This is all independent of URL structure -- the change I'm describing doesn't require changing any URLs.)

Alternatively, you can write whatever matching rules you want. Every liquid-fire helper allows matching by value, using `fromValue` or `toValue`. In the case of a `liquid-outlet`, the value is Ember's internal and undocumented outletState object (which we [hope to replace with a nicely documented public API](https://github.com/emberjs/rfcs/pull/95)). So you can do something like:

```js
this.transition(
    this.fromRoute('packages'),
    this.toRoute('profile'),
    this.toValue(outletState => {
        // do whatever checking you want inside `outletState` and return true if it should match.
        // the exact format of outletState is not currently public API and is subject to change when 
        // you upgrade Ember or liquid-fire.
        debugger;
        return true;
    }),
    this.use('toLeft'),
    this.reverse('toRight')
);
```

I get this question enough that I think we should make it Just Work the way people expect, so I am considering that for future releases.

**Comment by ptraceur** [comment]
I think I'm going to follow your suggestion and change hierarchy a bit to make things easier to make different animations. It would be nice you manage to make this possible in a future release. 

Thanks for everything, you make close the issue if you want.
Cheers :+1:
