### ISSUE TITLE
Breaks focusing element inside afterRender work

### ISSUE THREAD

**Issue by DuBistKomisch** [ember-animation/liquid-fire#531]
(This is specifically in regards to the ember-auto-focus addon's mechanism.)

Suppose you have a component rendered in a route which you transition into. If the transition is animated by liquid-fire, calling `focus` on an element within the component doesn't work in `afterRender` work, but it does work if the animation is commented out in `transitions.js`. Here's some code:

```javascript
  didInsertElement() {
    this._super(...arguments);

    console.warn('didInsertElement');
    // always works here
    // Ember.$(this.element).find('input')[0].focus();

    Ember.run.scheduleOnce('afterRender', this, () => {
      console.warn('afterRender');
      // only works here if not animated
      //Ember.$(this.element).find('input')[0].focus();
    });
  },
```

ember-auto-focus uses `afterRender` in its component because it wants to wait for contained elements to be rendered before trying to manipulate them. Within my own component I could just do it directly in `didInsertElement` of course, but I'd like to use a nice convenient addon instead of doing it all manually.

I don't really know enough about the Ember run loop or rendering to understand why this is breaking. The element does seem to exist if I log it to the console in `afterRender`. I suppose it could be some spec event quirk, as the behaviour is consistent across Chrome/Firefox/Safari.

**Comment by ef4** [comment]
My guess is that at the moment when ember-auto-focus tries to set focus, the content is set to `visibility: hidden` by liquid-fire so it isn't eligible for focus.

(Content starts hidden so that it doesn't flash in its final location before animations have a chance to move things around.)

The most direct way to manage focus at the end of an animation would probably be to build a `focusAfter` transition. It would work much like [scrollThen](https://github.com/ember-animation/liquid-fire/blob/ee50dbce3fe1de703f615ce728e84ab8b3b01724/addon/transitions/scroll-then.js).

**Comment by DuBistKomisch** [comment]
Seems like you're right. I managed to throw together a `focusAfter` transition (which was much easier than I expected) which just takes a `selector` option and calls `focus()` on the first result, and it appears works.

I suppose the ideal solution in my case is to combine `focusAfter` and `ember-auto-focus` for cases where you transition into a route and where you load straight into a route respectively.

I can submit a PR with `focusAfter` if you think this sort of functionality is appropriate for liquid-fire.
