### ISSUE TITLE
explode/fly-to between two animated canvases

### ISSUE THREAD

**Issue by lukaiser** [ember-animation/liquid-fire#598]
I have a list of 3d renderings. When clicking on one ember changes to a detail route with an WebGL canvas of the object. I would love to use liquid-fire with fly-to to kind of zoom in to the thumbnail. Unfortunately it does not work...
I had a closer look at the explode code. And if I understand it correctly at the beginning of the animation a copy of the canvas gets made and this copy then has no connection to (in my case) the babylonjs object handling the rendering and therefor no rendering happens.

I am happy to work on that problem but would love to talk about the best way.

I currently can imagine the following scenario:

Instead of copying the canvas, we could move the canvas and replace it in the original place with a placeholder. And when the animation is over we move it back.
Where are the pitfalls?

Additional my canvas/component would need to get informed about the size change, as the aspect ratio changes. What about, if the animate function looks at the element, if it is a component and if it has a onLiquidFireResize function. If this is the case, the function gets called and the component can do what ever it wants to change its appearance.

I love your feedback and ideas!

Thanks for the grate work with liquid-fire!

Lukas

**Comment by ef4** [comment]
Much of what you need for this is already implemented in [ember-animated](https://github.com/ember-animation/ember-animated). If you explore the routes in the the demo app it has examples similar to what you describe.

ember-animated isn't documented or released yet. There are still some loose ends. My next step is to write a quest issue outlining what work remains so we can push it toward its first release. I strongly expect this will happen before EmberConf (March) because I'm already signed up to talk about it there!

**Comment by ef4** [comment]
(And to be clear, ember-animated is a low-level library that I intend to integrate beneath liquid-fire -- liquid-fire will continue to work and be supported)

**Comment by lukaiser** [comment]
Thanks for the fast feedback!
I will have a look at ember-animated.
Should I close the issue or should it stay open?

**Comment by ef4** [comment]
I will close this as I don't think it's immediately actionable by itself.
