### ISSUE TITLE
Visibility regression on latest v0.29.3 release with `ember-modal-dialog`

### ISSUE THREAD

**Issue by alexdiliberto** [ember-animation/liquid-fire#610]
Seeing a regression when using with an `ember-modal-dialog` animated `explode` modal type. Here is a reproduction repository with steps to show the bug:

https://github.com/alexdiliberto/liquid-fire-0.29.3-regression-using-ember-modal-dialog

This is the specific line change that introduces the regression: https://github.com/ember-animation/liquid-fire/pull/607/files#diff-5856713c422e7fbf65d5870770d00ddcL43

**Comment by ef4** [comment]
Thanks for the detailed reproduction. cc'ing @brettburley who worked on this area in case he has a chance to look at this bug before I do.

**Comment by brettburley** [comment]
It looks like it's an interaction between the new visibility settings and `liquid-wormhole`. It seems `liquid-wormhole` was relying on the behavior of `liquid-fire` applying `visibility: visible` to elements when they were animated. `liquid-wormhole` adds `visibility: hidden` to a few of the parents -- I assume so that the parent containers which it makes `100%` width and `100vh` height are not clickable.

Here's a patch for `liquid-wormhole` that appears to make the example provided by @alexdiliberto work: https://github.com/brettburley/liquid-wormhole/commit/7a9cd47a74fbfcb31ac5e551dd610f0fc5fcb271

Not sure the best path forward,
1. Fix `liquid-wormhole` so that it doesn't assume that elements get `visibility: visible` when they animate.
2. Lock `liquid-wormhole` to an earlier version of `liquid-fire`.
3. Revert the change in `liquid-fire`.

I _think_ the last is the least desirable, since it fixes a bug in core `liquid-fire` with nested transitions, but I'm not familiar enough with `liquid-wormhole` to know how it should be considered there.

**Comment by pzuraq** [comment]
I took a look at the proposed fix and it seems to be inline with what `liquid-wormhole` does today. Feel free to PR, happy to merge!

**Comment by brettburley** [comment]
@alexdiliberto the patch has been released in v2.1.5 of `liquid-wormwhole`: https://github.com/pzuraq/liquid-wormhole/pull/59

Can you confirm that this fixes your issue?

**Comment by alexdiliberto** [comment]
@brettburley Awesome, yea this fixes the issue! Thanks for the upstream PR! 🚀
