### ISSUE TITLE
Basic IE8 support

### ISSUE THREAD

**Issue by jerel** [ember-animation/liquid-fire#67]
Is liquid-fire supposed to support IE8 or what are your thoughts on supporting it? It looks like Velocity.js supports browsers back to IE8 and Android 2.3.

Currently we have an app that I am using liquid-fire on and I would like to provide at least an animation-less experience to IE8 but it fails at the import level:

```
Could not find module vendor/liquid-fire/transition
File: vendor.js, Line: 58, Column: 7
```

**Comment by jpweeks** [comment]
@Eptis I ran into this error as well. The issue is not caused by liquid-fire, but inconsistencies between native `Array.prototype.reduce` and Ember's polyfill implementation; see: emberjs/ember.js/issues/3437.
Using a more compatible [polyfill](https://github.com/inexorabletash/polyfill/blob/master/es5.js#L347-L386) fixes the issue.
